version: 2.0
jobs:
  build:
    docker:
      - image: clojure:boot-2.7.1

    workDir: /root/engaged

    steps:
      - checkout

      - restore_cache:
          keys:
            - engaged-jars-{{ checksum "build.boot" }}
            - engaged-jars-

      - run:
          name: Build/deploy
          environment:
            BOOT_AS_ROOT: "yes"
            BOOT_JVM_OPTIONS: "-client -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xmx2g -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -Xverify:none"
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
              boot production build deploy
            else
              boot production build target
            fi

      - save_cache:
          key: engaged-jars-{{ checksum "build.boot" }}
          paths:
            - /root/.m2
            - /root/bin
